### ISSUE TITLE
Hardware revision 3.3 without 100k resistor detected as legacy

### ISSUE THREAD

**Issue by etnoy** [kveilands/SAAB-CDC#12]
I had to debug this for a while until I found the issue. I have the v3.3 hardware but never realized I had to solder the R14 100k resistor. There never was an issue until now when the latest software does the auto-check and needs the 100k resistor. The 3.3 board was detected as legacy which means the RN52 can't be communicated with. The end result is that the blue/red led:s never flash and Bluetooth doesn't turn on.

I will need to solder the 100k resistor, of course, but the facts remain that the docs were never very clear on the function of R14, and perhaps there should be a warning when "Legacy" is detected? This would help people like me some debugging time :)

For those googling, I did a temp workaround by simply adding `hwRevisionCheckValue=38;` just before the line that says `switch (hwRevisionCheckValue) {`

**Comment by Edison517** [comment]
Well, had you populated the pcb correctly, you wouldn't have had this problem ;)

**Comment by etnoy** [comment]
Agreed! However, the resistor was not at all clear in the older building instructions. Let's leave this issue closed but still available for googlers :)
