### ISSUE TITLE
Forcing RN52 module to non-discoverable can't be undone without hard reset

### ISSUE THREAD

**Issue by sambthompson** [kveilands/SAAB-CDC#15]
If I test the "Set RN52 to non-discoverable" button (press and hold ``<<SEEK`` or ``3``), I can never re-enable discoverability unless I reset the BlueSaab with a power disconnect. I'm not sure if that means the `bt_reboot()` code is the problem, or the corresponding `bt_visible()` function is failing to set things up again properly.

**Comment by sambthompson** [comment]
@Edison517 has queried whether this was a previously reported issue and had been fixed on the [forum](http://bluesaab-forum.2349123.n4.nabble.com/Functions-currently-supported-by-the-software-tp123p782.html), but I've gone through the open and closed issues and I don't see any matching symptoms.

**Comment by Edison517** [comment]
I may be confusing functions that got fixed; the latest release fixed an issue where the module couldn't be put into discoverable mode. Are you sure you're using the latest version of software?

**Comment by sambthompson** [comment]
Yes, just downloaded from Karlis's master branch after the latest pull request. I can't see an obvious commit remark for the fix you describe, although there was a change where `bt_invisible()` was changed to `bt_reboot()`. Things seem to stop working after the `bt_reboot()`.

**Comment by sambthompson** [comment]
@Edison517, in response to your edit, yes the short press 3 & 6 buttons work fine for disconnect / reconnect. It's the long press/press and hold functions for changing the discoverability of the module or rebooting that seems to have an issue.

**Comment by sambthompson** [comment]
Further debugging reveals that the response from the reboot command is supposed to be "Reboot!" however this doesn't end in \r\n and is most often truncated. Without further responses from the RN52, the update() code gets trapped in a loop and won't send further commands, unless it's told it's not in command mode. Testing a fix.

**Comment by sambthompson** [comment]
In addition to the above, the core issue is that rebooting while PWREN is low prevents the reboot, and seems to cause a lock-up with futher PWREN toggles can't fix. Testing another fix.

**Comment by sambthompson** [comment]
Although PR #16 includes a fix for PWREN and command timeouts, there is still seems to be a problem with controlling discoverability/connectability via the IHU. Weird because volume controls work and it's the same interface. Further investigation needed.

**Comment by sambthompson** [comment]
Fixed in #16, commit 4a0b72e4194ae18ad42ae3638ad8464a7e765197. Was caused by the watch dog timer set too aggressively for allow the reboot/reset time, leading to a reboot loop. Now disabled watch dog during `setup()` function, re-enabled once `loop()` entered. Ready for 4.1.
