### ISSUE TITLE
v3.0 software doesn't work on pcb's prior to v3.3

### ISSUE THREAD

**Issue by Edison517** [kveilands/SAAB-CDC#5]
This latest software apparently does not allow the RN52 to boot properly because we're pulling AIC0 on RN52 high at boot, which the RN52 doesn't like.

This pin (Analog 0 on ATmega328) no longer goes to AIC0 on v3.3 pcbs (it goes to PWREN pin on RN52), so there's no problem with them.

**Comment by Edison517** [comment]
The fix is to remark one line inside the file RN52impl.cpp 
digitalWrite(BT_PWREN_PIN,HIGH);

**Comment by Edison517** [comment]
The fix is to remark one line inside the file RN52impl.cpp 
digitalWrite(BT_PWREN_PIN,HIGH);

**Comment by kveilands** [comment]
This issue has been addressed and fixed in software version 3.6. We now check for hardware revision via resistor divider network values and thus determine what hardware the code is running on and manage the pins accordingly.
