### ISSUE TITLE
Switching over to CDC mode doesn't always set BlueSaab to an active mode on SAAB 9-5s

### ISSUE THREAD

**Issue by kveilands** [kveilands/SAAB-CDC#7]
When switching over from Radio mode to CDC mode on IHU or if the IHU is left in CDC mode when the ignition is turned off, upon switching the car back on, the BlueSaab module is not always getting set to an active mode indicated by the "magic beep" (= first CAN frame has been detected on bus by BlueSaab). It is suspected that this is due to either improper CNF values of MCP2515 chip (responsible for CAN comms) or improper CDC status replies with regards to head unit.

**Comment by kveilands** [comment]
Typical set of status reports by an original SAAB CD changer when it's not playing anything but has a CD in slot #1 of the magazine:

SAAB CAN Sniffer v1.0 - June 2016
3C8 -> 20 0 7 1 FF FF FF D0 
Time gap: 633
3C8 -> 20 0 7 1 FF FF FF D0 
Time gap: 982
3C8 -> 20 0 7 1 FF FF FF D0 
Time gap: 990
3C8 -> 20 0 7 1 FF FF FF D0 
Time gap: 989

**Comment by kveilands** [comment]
Typical set of status reports by an original SAAB CD changer when it's playing track #1 of CD in slot #1 of the magazine:

SAAB CAN Sniffer v1.0 - June 2016
3C8 -> 20 0 7 41 1 0 0 D0 
Time gap: 550
3C8 -> A0 0 7 41 1 0 1 D0 
Time gap: 447
3C8 -> 20 0 7 41 1 0 1 D0 
Time gap: 543
3C8 -> A0 0 7 41 1 0 2 D0 
Time gap: 455
3C8 -> 20 0 7 41 1 0 2 D0 
Time gap: 534
3C8 -> A0 0 7 41 1 0 3 D0 
Time gap: 463
3C8 -> 20 0 7 41 1 0 3 D0 
Time gap: 527
3C8 -> A0 0 7 41 1 0 4 D0

**Comment by kveilands** [comment]
This issue has been addressed and fixed in software version 3.7. The fix was to narrow down event byte of an incoming frame that we had to react to and mark cdcActive value as true.

**Comment by etnoy** [comment]
Sounds great, will try to test soon.
